name: 'Project1Datavault'
version: '1.0'
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  Project1Datavault:

    staging:
      +materialized: view
      +schema: STAGING

    hubs:
      +materialized: table
      +schema: DV

    links:
      +materialized: table
      +schema: DV

    satellites:
      +materialized: table
      +schema: DV